services:
  db:
    image: postgres:16
    container_name: esquadrao_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esquadrao_development

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: esquadrao_redis

    ports:
      - "6379:6379"

  web:
    build: .

    container_name: esquadrao_web

    command: bin/rails server -b 0.0.0.0

    volumes:
      - .:/app

    ports:
      - "3000:3000"

    depends_on:
      - db
      - redis

    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

volumes:
  postgres_data:
